# Jekyll configuration

name: Welcome to my blog 
description: Bioinformatics blog from a biologist

# url is currently only used only for the RSS feed in feed.xml
url: https://svsuresh.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
baseurl: ''

# These can be '' to hide the Github or Gitlab nav buttons
github: "svsuresh"

permalink: /:title
paginate: 3

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']
exclude: ['README.md']
